# Generated by Django 4.1.8 on 2023-04-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
